services:
  postgres:
    image: postgres:14-alpine
    container_name: securebank-postgres
    environment:
      POSTGRES_DB: securebank
      POSTGRES_USER: bankadmin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankadmin -d securebank"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - securebank-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: securebank-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - securebank-network
    restart: unless-stopped

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: securebank-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      DATABASE_URL: postgresql://bankadmin:${DB_PASSWORD}@postgres:5432/securebank
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      ENCRYPTION_IV: ${ENCRYPTION_IV}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: securebank
      DB_USER: bankadmin
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/database:/app/database
    networks:
      - securebank-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Assure-toi d’avoir un Dockerfile.dev
    container_name: securebank-frontend
    depends_on:
      - app
    environment:
      REACT_APP_API_URL: http://app:3000/api   # Utilise le nom du service backend dans Docker
      REACT_APP_ENV: ${NODE_ENV}
      TZ: Africa/Tunis
    ports:
      - "3001:3000"  # Accès depuis localhost:3001
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    command: npm start
    networks:
      - securebank-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  securebank-network:
    driver: bridge
